[package]
symbol = "󰏗 "

[golang]
symbol = " "
format = '[$symbol]($style)'

[lua]
symbol = " "
format = '[$symbol]($style)'

[nodejs]
symbol = " "
format = '[$symbol]($style)'

[php]
symbol = " "
format = '[$symbol]($style)'

[docker_context]
symbol = " "
format = '[$symbol]($style)'
