# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  proxy:
    container_name: proxy
    image: nginx:latest
    network_mode: host
    ports:
      - "80:80/tcp"
    volumes:
      - './conf.d:/etc/nginx/sites-enabled'
    restart: unless-stopped
