name: "Flake check"
on:
  pull_request:
  push:
    paths:
      - 'nix/**'
jobs:
  tests:
    if: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        enable_kvm: true
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nix build
      working-directory: nix
    - run: nix flake check
      working-directory: nix
